export { ReactComponent as Logo } from './logo.svg';
export { ReactComponent as Loading } from './loading.svg';
export { ReactComponent as Search } from './search.svg';
export { ReactComponent as TopIcon } from './top-icon.svg';
export { ReactComponent as MovieIcon } from './movie-icon.svg';
export { ReactComponent as PopcornIcon } from './popcorn-icon.svg';
export { ReactComponent as StarIcon } from './star-icon.svg';
export { ReactComponent as HomeIcon } from './home-icon.svg';
export { ReactComponent as Triangle } from './ball-triangle.svg';
